version: "3"
services:
#  shop:
#    # replace username/repo:tag with your name and image details
#    image: localhost:5000/shop:latest
#    depends_on:
#      - psql
#    ports:
#      - "8080:8080"
#    networks:
#      - default
#     environment:
#       SPRING_PROFILES_ACTIVE: "dev"

  pricing-service:
    # replace username/repo:tag with your name and image details
    image: localhost:5000/pricing-service:latest
    depends_on:
      - psql
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      SPRING_PROFILES_ACTIVE: "dev"

  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:

volumes:
  postgres-data:

